# Generated by Django 5.2.8 on 2025-11-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='fch_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soporte',
            name='respuesta_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='est_spt',
            field=models.CharField(default='Pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='tp_spt',
            field=models.CharField(choices=[('queja', 'Queja'), ('reclamo', 'Reclamo'), ('novedad', 'Novedad'), ('solicitud', 'Solicitud')], max_length=30),
        ),
    ]
